Add to cart
pearllaw/jamazon pull request #10
Opened 2018-09-09 23:05 UTC by pearllaw

2018-09-09 23:06 UTC, pearllaw commented
![issue 3](https://user-images.githubusercontent.com/35009493/45269886-51567400-b44a-11e8-94f8-adbfe09d9e15.gif)

2018-09-10 16:05 UTC, thebearingedge requested changes
Ok, you're on your way. A couple things. 
1. Switch back to this branch and make the requested changes.
2. Please fix your layout of the item details, the image is too large. Try to make your layout look like the wireframe.
3. It's not a good idea to work ahead unless your open Pull Request is _perfect_. Otherwise you will end up with merge conflicts.

This is your current branching history:
![screenshot 2018-09-10 08 56 51](https://user-images.githubusercontent.com/7432943/45309431-890bfd00-b4d8-11e8-86a3-072c89632a26.png)

This is our goal:
![screenshot 2018-09-10 08 57 26](https://user-images.githubusercontent.com/7432943/45309451-93c69200-b4d8-11e8-9dc6-db75b2fec7b8.png)

2018-09-10 16:05 UTC, thebearingedge commented on main.js
> +// Function rendering cart item count
Please delete comments like this. The function and parameter names should be descriptive enough.

2018-09-10 16:05 UTC, thebearingedge commented on main.js
> +    renderCartCount(app.cart)
You are not doing anything with `renderCartCount`'s return value here.

2018-09-10 16:05 UTC, thebearingedge commented on main.js
> +    $view.appendChild(renderCartCount(app.cart))
Put a separate element in your HTML file to hold the rendered card count.

2018-09-10 16:05 UTC, thebearingedge commented on main.js
> +  if (app.view === 'details' || app.view === 'cart') {
The cart view is not until a later feature (view cart summary). The cart count should be visible at all times.

2018-09-10 16:08 UTC, thebearingedge commented
Please reopen when ready.

2018-09-10 20:33 UTC, pearllaw commented
![issue 3](https://user-images.githubusercontent.com/35009493/45322789-1ca3f480-b4fe-11e8-908b-2c879eddc8c4.gif)

2018-09-10 20:38 UTC, thebearingedge approved these changes

2018-09-10 20:38 UTC, merged